# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f36aa2a0c360958e272843e995d29d4f1e2e89dc864125404a9a6645686be5654a45c4dd2afdf5408b2f4e7399eae1b5d4371f5b11d1c7dcf20e92672c262ae

test:
  secret_key_base: 0a01a87da105a1f41ee03f65ca305c8bd8d15d7450b0ffe70b994e4e8fc8a2aa4f52300b8677180469ed672ecbfa97540d98017e0552a19b32bb376f2245a6e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
